# Generated by Django 5.0.4 on 2024-04-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_age_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
